import React, { FormEvent, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { CalendarDays, Check, ChevronRight, CircleDollarSign, CirclePlus, Home, List, MoreHorizontal, PiggyBank, Settings, Trash2, X } from 'lucide-react';
import './styles.css';

type TxType = 'expense' | 'income' | 'reserve' | 'debt_payment';
type Transaction = { id: string; type: TxType; amount: number; date: string; categoryId?: string; sourceId?: string };
type Category = { id: string; name: string; icon: string; archived?: boolean };
type Source = { id: string; name: string; archived?: boolean };
type FuturePayment = { id: string; amount: number; date: string; categoryId: string; paid?: boolean };
type Debt = { initialAmount: number; nextPaymentDate: string; nextPaymentAmount: number };
type Plan = { month: string; plannedIncome: number; plannedReserve: number };
type Data = { onboarded: boolean; initialBalance: number; initialBalanceDate: string; categories: Category[]; sources: Source[]; transactions: Transaction[]; future: FuturePayment[]; debt: Debt; plans: Plan[] };
type Page = 'home' | 'operations' | 'plan' | 'settings';

const today = () => new Date().toISOString().slice(0, 10);
const monthKey = (date = today()) => date.slice(0, 7);
const uid = () => crypto.randomUUID();
const money = (n: number) => `${new Intl.NumberFormat('ru-RU', { maximumFractionDigits: 0 }).format(n)} ₽`;
const dateLabel = (date: string) => new Intl.DateTimeFormat('ru-RU', { day: 'numeric', month: 'short' }).format(new Date(`${date}T12:00:00`));
const defaultData = (): Data => ({
  onboarded: false, initialBalance: 0, initialBalanceDate: today(),
  categories: [['products','Продукты','🛒'],['transport','Транспорт','🚌'],['utilities','Коммунальные платежи','⌂'],['subscriptions','Подписки','◉'],['connection','Связь','⌁'],['debts','Долги','◎'],['unexpected','Непредвиденные расходы','!'],['other','Прочее','•••']].map(([id,name,icon]) => ({ id,name,icon })),
  sources: [['salary','Зарплата'],['self','Самозанятость'],['interest','Проценты по вкладу'],['other','Прочее']].map(([id,name]) => ({ id,name })),
  transactions: [], future: [], debt: { initialAmount: 0, nextPaymentDate: today(), nextPaymentAmount: 0 }, plans: []
});

async function loadData(): Promise<Data> {
  return new Promise((resolve) => { const r = indexedDB.open('moi-finansy', 1); r.onupgradeneeded = () => r.result.createObjectStore('state'); r.onsuccess = () => { const tx = r.result.transaction('state', 'readonly').objectStore('state').get('data'); tx.onsuccess = () => resolve(tx.result || defaultData()); tx.onerror = () => resolve(defaultData()); }; r.onerror = () => resolve(defaultData()); });
}
async function saveData(data: Data) { return new Promise<void>((resolve) => { const r = indexedDB.open('moi-finansy', 1); r.onsuccess = () => { const tx = r.result.transaction('state', 'readwrite'); tx.objectStore('state').put(data, 'data'); tx.oncomplete = () => resolve(); }; }); }

function App() {
  const [data, setData] = useState<Data | null>(null); const [page, setPage] = useState<Page>('home');
  const [sheet, setSheet] = useState<'expense'|'income'|'reserve'|'future'|'futureForm'|'debt'|'onboard'|null>(null); const [editing, setEditing] = useState<Transaction | null>(null); const [paying, setPaying] = useState<FuturePayment | null>(null);
  useEffect(() => { loadData().then(setData); if ('serviceWorker' in navigator) navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`); }, []);
  const commit = (next: Data) => { setData(next); saveData(next); };
  const calc = useMemo(() => {
    if (!data) return null; const month = monthKey(); const plan = data.plans.find((p) => p.month === month) || { month, plannedIncome: 0, plannedReserve: 0 };
    const income = data.transactions.filter((t) => t.type === 'income').reduce((s,t) => s + t.amount, 0);
    const expenses = data.transactions.filter((t) => t.type === 'expense'); const debtPaid = data.transactions.filter((t) => t.type === 'debt_payment').reduce((s,t) => s + t.amount, 0);
    const totalExpenses = expenses.reduce((s,t) => s + t.amount, 0); const reserves = data.transactions.filter((t) => t.type === 'reserve').reduce((s,t) => s + t.amount, 0);
    const monthExpenses = expenses.filter((t) => monthKey(t.date) === month).reduce((s,t) => s + t.amount, 0);
    const balance = data.initialBalance + income - totalExpenses - debtPaid; const reserve = reserves - debtPaid; const limit = plan.plannedIncome - plan.plannedReserve;
    return { month, plan, income, totalExpenses, monthExpenses, balance, reserve, free: balance - reserve, limit, remaining: limit - monthExpenses, remainingReserve: plan.plannedReserve - reserve, debtRemaining: data.debt.initialAmount - debtPaid };
  }, [data]);
  if (!data || !calc) return <main className="loading">Загружаем ваши финансы…</main>;
  if (!data.onboarded) return <Onboarding data={data} onDone={commit} />;
  const categoriesSpent = data.categories.map((c) => ({ ...c, amount: data.transactions.filter((t) => t.type === 'expense' && t.categoryId === c.id && monthKey(t.date) === calc.month).reduce((s,t) => s+t.amount,0) })).filter((c) => c.amount > 0);
  const imminent = data.future.filter((p) => !p.paid && Math.round((new Date(`${p.date}T12:00`).getTime() - new Date(`${today()}T12:00`).getTime()) / 86400000) <= 1 && p.date >= today());
  const addTx = (tx: Omit<Transaction,'id'>) => { const next = { ...data, transactions: editing ? data.transactions.map((item) => item.id === editing.id ? { ...tx, id: item.id } : item) : [...data.transactions, { ...tx, id: uid() }] }; commit(next); setEditing(null); setSheet(null); setPaying(null); };
  const removeTx = (id: string) => { if (confirm('Удалить эту операцию?')) commit({ ...data, transactions: data.transactions.filter((t) => t.id !== id) }); };
  return <main className="app">
    {page === 'home' && <HomePage calc={calc} categories={categoriesSpent} imminent={imminent} onOpen={() => setSheet('future')} />}
    {page === 'operations' && <Operations data={data} onEdit={(t) => { setEditing(t); setSheet(t.type === 'income' ? 'income' : t.type === 'reserve' ? 'reserve' : 'expense'); }} onDelete={removeTx} onPay={(p) => { setPaying(p); setSheet('expense'); }} />}
    {page === 'plan' && <PlanPage data={data} calc={calc} onSave={(plan) => commit({ ...data, plans: [...data.plans.filter((p) => p.month !== calc.month), plan] })} onDebt={() => setSheet('debt')} />}
    {page === 'settings' && <SettingsPage data={data} onSave={commit} />}
    <button className="fab" aria-label="Добавить операцию" onClick={() => setSheet('future')}> <CirclePlus size={28} /> </button>
    <nav>{([['home','Главная',Home],['operations','Операции',List],['plan','План',CircleDollarSign],['settings','Настройки',Settings]] as const).map(([key,label,Icon]) => <button key={key} className={page===key?'active':''} onClick={() => setPage(key)}><Icon size={21}/><span>{label}</span></button>)}</nav>
    {sheet === 'future' && <ChoiceSheet onClose={() => setSheet(null)} onPick={(v) => setSheet(v)} />}
    {sheet && ['expense','income','reserve'].includes(sheet) && <TransactionSheet type={sheet as 'expense'|'income'|'reserve'} data={data} initial={editing || (paying ? { type:'expense', amount: paying.amount, date: paying.date, categoryId: paying.categoryId } : undefined)} onClose={() => { setSheet(null); setEditing(null); setPaying(null); }} onSave={(tx) => { addTx(tx); if (paying) commit({ ...data, future: data.future.map((p) => p.id === paying.id ? { ...p, paid: true } : p), transactions: editing ? data.transactions : [...data.transactions, { ...tx, id: uid() }] }); }} />}
    {sheet === 'future' && null}
    {sheet === 'debt' && <DebtSheet debt={data.debt} calc={calc} onClose={() => setSheet(null)} onSave={(debt) => { commit({ ...data, debt }); setSheet(null); }} onPay={(amount) => { addTx({ type:'debt_payment',amount,date:today() }); }} />}
    {sheet === 'futureForm' && <FutureSheet data={data} onClose={() => setSheet(null)} onSave={(payment) => { commit({ ...data, future:[...data.future,{...payment,id:uid()}] }); setSheet(null); }} />}
  </main>;
}

function Onboarding({ data, onDone }: { data: Data; onDone: (d:Data)=>void }) { const [step,setStep]=useState(0); const [balance,setBalance]=useState(''); const [debt,setDebt]=useState(''); const [income,setIncome]=useState(''); const [reserve,setReserve]=useState(''); const finish=()=>onDone({...data,onboarded:true,initialBalance:Number(balance)||0,debt:{...data.debt,initialAmount:Number(debt)||0},plans:[{month:monthKey(),plannedIncome:Number(income)||0,plannedReserve:Number(reserve)||0}]}); return <main className="onboard"><div className="brand">Мои финансы</div><div className="onboard-card"><p className="eyebrow">Шаг {step+1} из 3</p>{step===0&&<><h1>С чего начинаем?</h1><p>Укажите, сколько денег у вас есть сейчас.</p><MoneyInput value={balance} onChange={setBalance}/></>}{step===1&&<><h1>Ближайший долг</h1><p>Введите текущую сумму долга. Её можно изменить позже.</p><MoneyInput value={debt} onChange={setDebt}/></>}{step===2&&<><h1>План на месяц</h1><p>Лимит автоматически вычтет резерв на долг.</p><label>Планируемый доход<MoneyInput value={income} onChange={setIncome}/></label><label>Резерв на долг<MoneyInput value={reserve} onChange={setReserve}/></label></>}<button className="primary" onClick={()=>step<2?setStep(step+1):finish()}>{step<2?'Продолжить':'Открыть приложение'} <ChevronRight size={18}/></button></div></main> }

function HomePage({calc,categories,imminent,onOpen}:{calc:any;categories:any[];imminent:FuturePayment[];onOpen:()=>void}) { const total=categories.reduce((s,c)=>s+c.amount,0); return <section><header><h1>Главная</h1><div className="avatar">●</div></header>{imminent[0]&&<button className="reminder" onClick={onOpen}><CalendarDays size={18}/> Завтра: запланированный платёж {money(imminent[0].amount)}</button>}<div className="hero"><p>Осталось потратить</p><strong>{money(calc.remaining)}</strong><div className="hero-stats"><span>Общий остаток <b>{money(calc.balance)}</b></span><span>Свободные деньги <b>{money(calc.free)}</b></span></div></div><h2>Расходы за месяц</h2>{total ? <div className="chart-wrap"><div className="donut" style={{background:`conic-gradient(#6FAE52 0 ${categories[0]?.amount/total*100}%, #315525 ${categories[0]?.amount/total*100}% 100%)`}}><i/></div><div>{categories.map((c)=><div className="legend" key={c.id}><span>{c.icon} {c.name}</span><b>{money(c.amount)}</b></div>)}</div></div> : <div className="empty">Добавьте первую трату — здесь появится распределение по категориям.</div>}</section> }

function Operations({data,onEdit,onDelete,onPay}:{data:Data;onEdit:(t:Transaction)=>void;onDelete:(id:string)=>void;onPay:(p:FuturePayment)=>void}) { const items=[...data.transactions].sort((a,b)=>b.date.localeCompare(a.date)); return <section><header><h1>Операции</h1></header><div className="operation-summary"><span>Доходы <b>{money(items.filter(x=>x.type==='income').reduce((s,x)=>s+x.amount,0))}</b></span><span>Расходы <b>{money(items.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amount,0))}</b></span></div>{items.length===0&&!data.future.length?<div className="empty">Операций пока нет. Нажмите «+», чтобы добавить первую.</div>:<div className="list">{items.map(t=><article key={t.id} className="operation"><div><strong>{t.type==='income'?'Доход':t.type==='reserve'?'Резерв':t.type==='debt_payment'?'Платёж по долгу':data.categories.find(c=>c.id===t.categoryId)?.name||'Расход'}</strong><small>{dateLabel(t.date)}</small></div><b className={t.type==='income'?'positive':''}>{t.type==='income'?'+':'−'}{money(t.amount)}</b><button onClick={()=>onEdit(t)} aria-label="Изменить">•••</button><button onClick={()=>onDelete(t.id)} aria-label="Удалить"><Trash2 size={16}/></button></article>)}{data.future.map(p=><article key={p.id} className="operation future"><div><strong>{data.categories.find(c=>c.id===p.categoryId)?.name||'Платёж'}</strong><small>{dateLabel(p.date)} · {p.paid?'Оплачено':'Ожидается'}</small></div><b>{money(p.amount)}</b>{!p.paid&&<button className="mini" onClick={()=>onPay(p)}>Оплачено</button>}</article>)}</div>}</section> }

function PlanPage({data,calc,onSave,onDebt}:{data:Data;calc:any;onSave:(p:Plan)=>void;onDebt:()=>void}) { const [income,setIncome]=useState(String(calc.plan.plannedIncome||'')); const [reserve,setReserve]=useState(String(calc.plan.plannedReserve||'')); return <section><header><h1>План</h1></header><div className="hero"><p>Лимит на месяц</p><strong>{money((Number(income)||0)-(Number(reserve)||0))}</strong><div className="progress"><i style={{width:`${Math.max(0,Math.min(100, calc.monthExpenses / Math.max(1,(Number(income)||0)-(Number(reserve)||0))*100))}%`}}/></div></div><label>Планируемый доход<MoneyInput value={income} onChange={setIncome}/></label><label>Плановый резерв на долг<MoneyInput value={reserve} onChange={setReserve}/></label><button className="primary" onClick={()=>onSave({month:calc.month,plannedIncome:Number(income)||0,plannedReserve:Number(reserve)||0})}>Сохранить план <Check size={18}/></button><div className="reserve-card"><p>Фактически отложено</p><strong>{money(calc.reserve)}</strong><small>Осталось отложить: {money(calc.remainingReserve)}</small><button onClick={onDebt}>Управлять долгом <ChevronRight size={16}/></button></div></section> }

function SettingsPage({data,onSave}:{data:Data;onSave:(d:Data)=>void}) { const [balance,setBalance]=useState(String(data.initialBalance)); const [name,setName]=useState(''); const add=()=>{if(name.trim()) {onSave({...data,categories:[...data.categories,{id:uid(),name:name.trim(),icon:'•'}]});setName('');}}; return <section><header><h1>Настройки</h1></header><label>Начальный остаток<MoneyInput value={balance} onChange={setBalance}/></label><button className="secondary" onClick={()=>onSave({...data,initialBalance:Number(balance)||0})}>Сохранить остаток</button><h2>Категории</h2><div className="settings-list">{data.categories.map(c=><div key={c.id}>{c.icon} {c.name}<button onClick={()=>onSave({...data,categories:data.categories.map(x=>x.id===c.id?{...x,archived:!x.archived}:x)})}>{c.archived?'Вернуть':'Архивировать'}</button></div>)}</div><div className="inline-add"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Новая категория"/><button onClick={add}>Добавить</button></div><h2>Источники дохода</h2><div className="settings-list">{data.sources.map(s=><div key={s.id}>{s.name}<button onClick={()=>onSave({...data,sources:data.sources.map(x=>x.id===s.id?{...x,archived:!x.archived}:x)})}>{s.archived?'Вернуть':'Архивировать'}</button></div>)}</div></section> }

function ChoiceSheet({onClose,onPick}:{onClose:()=>void;onPick:(x:any)=>void}) { return <Sheet onClose={onClose}><h2>Добавить</h2>{[['expense','Расход'],['income','Доход'],['reserve','Резерв на долг'],['future','Будущий платёж']].map(([key,label])=><button className="choice" key={key} onClick={()=>key==='future'?onPick('futureForm'):onPick(key)}>{label}<ChevronRight/></button>)}</Sheet> }
function TransactionSheet({type,data,initial,onClose,onSave}:{type:'expense'|'income'|'reserve';data:Data;initial?:Partial<Transaction>;onClose:()=>void;onSave:(x:Omit<Transaction,'id'>)=>void}) { const [amount,setAmount]=useState(String(initial?.amount||''));const [date,setDate]=useState(initial?.date||today());const [ref,setRef]=useState(initial?.categoryId||initial?.sourceId||''); const options=type==='income'?data.sources.filter(x=>!x.archived):data.categories.filter(x=>!x.archived);return <Sheet onClose={onClose}><h2>{type==='expense'?'Расход':type==='income'?'Доход':'Резерв'}</h2><label>Сумма<MoneyInput value={amount} onChange={setAmount}/></label>{type!=='reserve'&&<label>{type==='income'?'Источник':'Категория'}<select value={ref} onChange={e=>setRef(e.target.value)}><option value="">Выберите</option>{options.map(x=><option key={x.id} value={x.id}>{('icon' in x?x.icon+' ':'')+x.name}</option>)}</select></label>}<label>Дата<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="primary" disabled={!amount|| (type!=='reserve'&&!ref)} onClick={()=>onSave({type,amount:Number(amount),date,...(type==='income'?{sourceId:ref}:type==='expense'?{categoryId:ref}:{})})}>Сохранить <Check size={18}/></button></Sheet> }
function FutureSheet({data,onClose,onSave}:{data:Data;onClose:()=>void;onSave:(p:Omit<FuturePayment,'id'|'paid'>)=>void}){const [amount,setAmount]=useState('');const [date,setDate]=useState(today());const [categoryId,setCategoryId]=useState('');return <Sheet onClose={onClose}><h2>Будущий платёж</h2><p className="muted">Это напоминание. Оно не уменьшит баланс и лимит до оплаты.</p><label>Сумма<MoneyInput value={amount} onChange={setAmount}/></label><label>Категория<select value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">Выберите</option>{data.categories.filter(c=>!c.archived).map(c=><option key={c.id} value={c.id}>{c.icon} {c.name}</option>)}</select></label><label>Дата<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="primary" disabled={!amount||!categoryId} onClick={()=>onSave({amount:Number(amount),date,categoryId})}>Сохранить <Check size={18}/></button></Sheet>}
function DebtSheet({debt,calc,onClose,onSave,onPay}:{debt:Debt;calc:any;onClose:()=>void;onSave:(d:Debt)=>void;onPay:(x:number)=>void}) {const [total,setTotal]=useState(String(debt.initialAmount));const [amount,setAmount]=useState(String(debt.nextPaymentAmount));const [date,setDate]=useState(debt.nextPaymentDate);const [pay,setPay]=useState('');return <Sheet onClose={onClose}><h2>Долг</h2><p className="muted">Текущий остаток: <b>{money(calc.debtRemaining)}</b></p><label>Первоначальная сумма<MoneyInput value={total} onChange={setTotal}/></label><label>Ближайший платёж<MoneyInput value={amount} onChange={setAmount}/></label><label>Дата платежа<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="secondary" onClick={()=>onSave({initialAmount:Number(total)||0,nextPaymentAmount:Number(amount)||0,nextPaymentDate:date})}>Сохранить данные</button><label>Зафиксировать платёж<MoneyInput value={pay} onChange={setPay}/></label><button className="primary" disabled={!pay} onClick={()=>{onPay(Number(pay));onClose();}}>Подтвердить платёж</button></Sheet> }
function Sheet({children,onClose}:{children:React.ReactNode;onClose:()=>void}){return <div className="overlay"><div className="sheet"><button className="close" onClick={onClose}><X/></button>{children}</div></div>}
function MoneyInput({value,onChange}:{value:string;onChange:(x:string)=>void}){return <div className="money-input"><input inputMode="numeric" value={value} onChange={e=>onChange(e.target.value.replace(/\D/g,''))} placeholder="0"/><span>₽</span></div>}

createRoot(document.getElementById('root')!).render(<App />);
